### ISSUE TITLE
It seems your results are slightly different from Portfolio Visualizer's. Do you know the reason?

### ISSUE THREAD

**Issue by physixfan** [linzebing/inverse_volatility_caculation#1]
See title.

**Comment by linzebing** [comment]
I'm just using the closing price of each day, not sure if it matters.

Computation is calculating the sample standard deviation of logarithmic returns. I don't have a finance background so someone may correct me - the code is straightforward.

**Comment by physixfan** [comment]
I checked your code, and if I remove the "math.log" the result is the same as Portfolio Visualizer's. Is there any good reason to use the logarithmic return?

**Comment by linzebing** [comment]
> I checked your code, and if I remove the "math.log" the result is the same as Portfolio Visualizer's. Is there any good reason to use the logarithmic return?

I mainly referred to https://en.wikipedia.org/wiki/Volatility_(finance), and it tells me to use logarithmic. There are indeed two ways to calculate volatility (https://wiki.mbalib.com/wiki/%E5%8E%86%E5%8F%B2%E6%B3%A2%E5%8A%A8%E7%8E%87), but seems using logarithmic is the mainstream from what I see. I will add an option to allow users to print results based on price percentage changes.

**Comment by physixfan** [comment]
Yeah I did some research as well after the previous comment. It seems the log return is indeed a better choice. Portfolio Visualizer is too simple.
